version: '3.8'
x-backend: &backend
  build: .
  ports:
    - "8080:8080"
  volumes:
    - ./:/app
  restart: unless-stopped
  depends_on:
    - postgres
  environment:
    APP_NAME: 'test-vk'
    APP_DEBUG: 'true'
    L5_SWAGGER_CONST_HOST: 'http://0.0.0.0:8080'
    APP_KEY: 'base64:d1k91AgNcf1g7t/SVxBwE3u4NFK/I3vMH8Gyzl2Rvrs='
    JWT_SECRET: 'YXvBW18QVJTIXho84WSseH12yQ32JdQYC5PmL8JzBuzcSz1YUnHfTUFG73ndNA1S'
    DB_CONNECTION: pgsql
    DB_HOST: postgres
    DB_PORT: 5432
    DB_DATABASE: app
    DB_USERNAME: postgres
    DB_PASSWORD: password
    WAIT_HOSTS: postgres:5432

services:
  backend:
    <<: *backend

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: "5432"
    ports:
      - "5050:5432"
    restart: unless-stopped
    depends_on:
      - postgres

  composer:
    image: composer:2.1.12
    working_dir: /composer
    volumes:
      - "./:/composer"
    command: composer install --ignore-platform-reqs
